-- ============================================
-- EMERGENCY FIX: Reset and properly categorize all vacancies
-- ============================================

-- 1. First, let's see what we have now
SELECT 'CURRENT STATE' as info;
SELECT 
  COALESCE(NULLIF(category, ''), 'EMPTY/NULL') as category,
  COUNT(*) as count
FROM vacancies
GROUP BY category
ORDER BY count DESC
LIMIT 10;

-- 2. Show some examples of broken IT vacancies
SELECT 'SAMPLE IT VACANCIES (should be IT but maybe not)' as info;
SELECT title, category, company
FROM vacancies
WHERE LOWER(title) LIKE '%программист%'
LIMIT 5;

-- 3. EMERGENCY FIX: Update categories properly
-- First reset all to NULL to start fresh
UPDATE vacancies SET category = NULL;

-- Now categorize using ILIKE (case-insensitive LIKE)
-- IT Category
UPDATE vacancies
SET category = 'ИТ'
WHERE title ILIKE '%программист%'
   OR title ILIKE '%разработчик%'
   OR title ILIKE '%developer%'
   OR title ILIKE '%инженер-программист%'
   OR title ILIKE '%frontend%'
   OR title ILIKE '%backend%'
   OR title ILIKE '%fullstack%'
   OR title ILIKE '%devops%'
   OR title ILIKE '%qa%'
   OR title ILIKE '%тестировщик%'
   OR title ILIKE '%javascript%'
   OR title ILIKE '%java%'
   OR title ILIKE '%python%'
   OR title ILIKE '%php%'
   OR title ILIKE '%1с%'
   OR title ILIKE '%1c%'
   OR title ILIKE '%bitrix%'
   OR title ILIKE '%битрикс%'
   OR title ILIKE '%web%'
   OR title ILIKE '%веб%'
   OR title ILIKE '%mobile%'
   OR title ILIKE '%мобильн%'
   OR title ILIKE '%react%'
   OR title ILIKE '%angular%'
   OR title ILIKE '%vue%'
   OR title ILIKE '%node%'
   OR title ILIKE '%sql%'
   OR title ILIKE '%it %'
   OR title ILIKE '%айти%'
   OR title ILIKE '%системный администратор%'
   OR title ILIKE '%сисадмин%'
   OR title ILIKE '%data scientist%'
   OR title ILIKE '%android%'
   OR title ILIKE '%ios%'
   OR title ILIKE '%golang%'
   OR title ILIKE '%ruby%'
   OR title ILIKE '%c++%'
   OR title ILIKE '%c#%'
   OR title ILIKE '.net%'
   OR title ILIKE '%docker%'
   OR title ILIKE '%kubernetes%'
   OR title ILIKE '%cloud%'
   OR title ILIKE '%кибербезопасность%'
   OR title ILIKE '%security%';

-- Medicine Category
UPDATE vacancies
SET category = 'Медицина'
WHERE category IS NULL
  AND (
    title ILIKE '%врач%'
    OR title ILIKE '%медицинский%'
    OR title ILIKE '%медсестра%'
    OR title ILIKE '%медбрат%'
    OR title ILIKE '%фельдшер%'
    OR title ILIKE '%стоматолог%'
    OR title ILIKE '%хирург%'
    OR title ILIKE '%терапевт%'
    OR title ILIKE '%педиатр%'
    OR title ILIKE '%кардиолог%'
    OR title ILIKE '%невролог%'
    OR title ILIKE '%офтальмолог%'
    OR title ILIKE '%акушер%'
    OR title ILIKE '%гинеколог%'
    OR title ILIKE '%уролог%'
    OR title ILIKE '%дерматолог%'
    OR title ILIKE '%психиатр%'
    OR title ILIKE '%психолог%'
    OR title ILIKE '%фармацевт%'
    OR title ILIKE '%провизор%'
    OR title ILIKE '%лаборант%'
    OR title ILIKE '%массажист%'
    OR title ILIKE '%реабилитолог%'
    OR title ILIKE '%диетолог%'
    OR title ILIKE '%логопед%'
    OR title ILIKE '%дефектолог%'
    OR title ILIKE '%рентгенолог%'
    OR title ILIKE '%анестезиолог%'
    OR title ILIKE '%реаниматолог%'
    OR title ILIKE '%инфекционист%'
    OR title ILIKE '%онколог%'
    OR title ILIKE '%эндокринолог%'
    OR title ILIKE '%гастроэнтеролог%'
    OR title ILIKE '%пульмонолог%'
    OR title ILIKE '%нефролог%'
    OR title ILIKE '%иммунолог%'
    OR title ILIKE '%аллерголог%'
    OR title ILIKE '%травматолог%'
    OR title ILIKE '%ортопед%'
    OR title ILIKE '%косметолог%'
    OR title ILIKE '%зубной%'
    OR title ILIKE '%дантист%'
  );

-- Engineering Category
UPDATE vacancies
SET category = 'Инженерия'
WHERE category IS NULL
  AND (
    title ILIKE '%инженер%'
    OR title ILIKE '%конструктор%'
    OR title ILIKE '%проектировщик%'
    OR title ILIKE '%технолог%'
    OR title ILIKE '%механик%'
    OR title ILIKE '%электрик%'
    OR title ILIKE '%электронщик%'
    OR title ILIKE '%сварщик%'
    OR title ILIKE '%токарь%'
    OR title ILIKE '%фрезеровщик%'
    OR title ILIKE '%слесарь%'
    OR title ILIKE '%машинист%'
    OR title ILIKE '%оператор станка%'
    OR title ILIKE '%чпу%'
    OR title ILIKE '%cnc%'
    OR title ILIKE '%энергетик%'
    OR title ILIKE '%строитель%'
    OR title ILIKE '%прораб%'
    OR title ILIKE '%мастер участка%'
    OR title ILIKE '%архитектор%'
    OR title ILIKE '%геодезист%'
    OR title ILIKE '%геолог%'
    OR title ILIKE '%нефтяник%'
    OR title ILIKE '%газовщик%'
    OR title ILIKE '%химик%'
    OR title ILIKE '%эколог%'
    OR title ILIKE '%сантехник%'
    OR title ILIKE '%электромонтер%'
    OR title ILIKE '%монтажник%'
    OR title ILIKE '%сборщик%'
    OR title ILIKE '%наладчик%'
    OR title ILIKE '%метролог%'
    OR title ILIKE '%стандартист%'
    OR title ILIKE '%техник%'
    OR title ILIKE '%контролер%'
    OR title ILIKE '%маляр%'
    OR title ILIKE '%штукатур%'
    OR title ILIKE '%плиточник%'
    OR title ILIKE '%отделочник%'
    OR title ILIKE '%плотник%'
    OR title ILIKE '%столяр%'
    OR title ILIKE '%электросварщик%'
    OR title ILIKE '%газосварщик%'
    OR title ILIKE '%арматурщик%'
    OR title ILIKE '%бетонщик%'
    OR title ILIKE '%крановщик%'
    OR title ILIKE '%машинист крана%'
    OR title ILIKE '%машинист экскаватора%'
    OR title ILIKE '%машинист бульдозера%'
    OR title ILIKE '%тракторист%'
    OR title ILIKE '%водитель погрузчика%'
    OR title ILIKE '%карщик%'
  );

-- Education Category
UPDATE vacancies
SET category = 'Педагогика'
WHERE category IS NULL
  AND (
    title ILIKE '%учитель%'
    OR title ILIKE '%преподаватель%'
    OR title ILIKE '%педагог%'
    OR title ILIKE '%воспитатель%'
    OR title ILIKE '%няня%'
    OR title ILIKE '%методист%'
    OR title ILIKE '%репетитор%'
    OR title ILIKE '%тьютор%'
    OR title ILIKE '%завуч%'
    OR title ILIKE '%директор школы%'
    OR title ILIKE '%директор детского сада%'
    OR title ILIKE '%заведующий%'
    OR title ILIKE '%декан%'
    OR title ILIKE '%ректор%'
    OR title ILIKE '%проректор%'
    OR title ILIKE '%завкафедрой%'
    OR title ILIKE '%аспирант%'
    OR title ILIKE '%старший преподаватель%'
    OR title ILIKE '%доцент%'
    OR title ILIKE '%профессор%'
    OR title ILIKE '%научный сотрудник%'
    OR title ILIKE '%исследователь%'
    OR title ILIKE '%логопед%'
    OR title ILIKE '%дефектолог%'
    OR title ILIKE '%психолог образовательный%'
    OR title ILIKE '%социальный педагог%'
    OR title ILIKE '%инструктор%'
    OR title ILIKE '%тренер%'
    OR title ILIKE '%преподаватель вождения%'
    OR title ILIKE '%учитель вождения%'
  );

-- Economics Category
UPDATE vacancies
SET category = 'Экономика'
WHERE category IS NULL
  AND (
    title ILIKE '%бухгалтер%'
    OR title ILIKE '%экономист%'
    OR title ILIKE '%финансист%'
    OR title ILIKE '%аудитор%'
    OR title ILIKE '%кредитный специалист%'
    OR title ILIKE '%кредитный эксперт%'
    OR title ILIKE '%специалист по кредитованию%'
    OR title ILIKE '%банкир%'
    OR title ILIKE '%сотрудник банка%'
    OR title ILIKE '%кассир банка%'
    OR title ILIKE '%операционист%'
    OR title ILIKE '%инвестиционный%'
    OR title ILIKE '%аналитик%'
    OR title ILIKE '%финансовый аналитик%'
    OR title ILIKE '%экономический аналитик%'
    OR title ILIKE '%бизнес-аналитик%'
    OR title ILIKE '%системный аналитик%'
    OR title ILIKE '%маркетолог%'
    OR title ILIKE '%специалист по маркетингу%'
    OR title ILIKE '%smm%'
    OR title ILIKE '%seo%'
    OR title ILIKE '%контекстная реклама%'
    OR title ILIKE '%таргетолог%'
    OR title ILIKE '%копирайтер%'
    OR title ILIKE '%content manager%'
    OR title ILIKE '%менеджер по продажам%'
    OR title ILIKE '%менеджер по работе с клиентами%'
    OR title ILIKE '%менеджер по ключевым клиентам%'
    OR title ILIKE '%account manager%'
    OR title ILIKE '%sales manager%'
    OR title ILIKE '%торговый представитель%'
    OR title ILIKE '%продавец%'
    OR title ILIKE '%продавец-консультант%'
    OR title ILIKE '%продавец-кассир%'
    OR title ILIKE '%кассир%'
    OR title ILIKE '%старший кассир%'
    OR title ILIKE '%консультант%'
    OR title ILIKE '%специалист по работе с клиентами%'
    OR title ILIKE '%клиентский менеджер%'
    OR title ILIKE '%hr%'
    OR title ILIKE '%hr-менеджер%'
    OR title ILIKE '%специалист по подбору персонала%'
    OR title ILIKE '%рекрутер%'
    OR title ILIKE '%кадровик%'
    OR title ILIKE '%специалист по кадрам%'
    OR title ILIKE '%директор по персоналу%'
    OR title ILIKE '%hr director%'
    OR title ILIKE '%менеджер по персоналу%'
    OR title ILIKE '%логист%'
    OR title ILIKE '%специалист по логистике%'
    OR title ILIKE '%менеджер по логистике%'
    OR title ILIKE '%транспортный логист%'
    OR title ILIKE '%склад%'
    OR title ILIKE '%кладовщик%'
    OR title ILIKE '%начальник склада%'
    OR title ILIKE '%менеджер склада%'
    OR title ILIKE '%комплектовщик%'
    OR title ILIKE '%грузчик%'
    OR title ILIKE '%экспедитор%'
    OR title ILIKE '%диспетчер%'
    OR title ILIKE '%транспортный диспетчер%'
    OR title ILIKE '%водитель%'
    OR title ILIKE '%водитель-экспедитор%'
    OR title ILIKE '%курьер%'
    OR title ILIKE '%закупщик%'
    OR title ILIKE '%менеджер по закупкам%'
    OR title ILIKE '%специалист по закупкам%'
    OR title ILIKE '%снабженец%'
    OR title ILIKE '%товаровед%'
    OR title ILIKE '%мерчандайзер%'
    OR title ILIKE '%промоутер%'
    OR title ILIKE '%хостес%'
    OR title ILIKE '%официант%'
    OR title ILIKE '%бармен%'
    OR title ILIKE '%бариста%'
    OR title ILIKE '%шеф-повар%'
    OR title ILIKE '%повар%'
    OR title ILIKE '%кондитер%'
    OR title ILIKE '%пекарь%'
    OR title ILIKE '%сушист%'
    OR title ILIKE '%пиццмейкер%'
    OR title ILIKE '%менеджер ресторана%'
    OR title ILIKE '%управляющий рестораном%'
    OR title ILIKE '%администратор ресторана%'
    OR title ILIKE '%менеджер гостиницы%'
    OR title ILIKE '%администратор гостиницы%'
    OR title ILIKE '%горничная%'
    OR title ILIKE '%портье%'
    OR title ILIKE '%секретарь%'
    OR title ILIKE '%делопроизводитель%'
    OR title ILIKE '%офис-менеджер%'
    OR title ILIKE '%администратор офиса%'
    OR title ILIKE '%помощник руководителя%'
    OR title ILIKE '%ассистент%'
    OR title ILIKE '%личный помощник%'
    OR title ILIKE '%переводчик%'
    OR title ILIKE '%стажер%'
    OR title ILIKE '%intern%'
    OR title ILIKE '%менеджер%'
    OR title ILIKE '%руководитель%'
    OR title ILIKE '%директор%'
    OR title ILIKE '%начальник отдела%'
    OR title ILIKE '%начальник управления%'
    OR title ILIKE '%заместитель директора%'
    OR title ILIKE '%генеральный директор%'
    OR title ILIKE '%коммерческий директор%'
    OR title ILIKE '%исполнительный директор%'
    OR title ILIKE '%финансовый директор%'
    OR title ILIKE '%операционный директор%'
    OR title ILIKE '%директор по маркетингу%'
    OR title ILIKE '%директор по продажам%'
    OR title ILIKE '%директор по персоналу%'
    OR title ILIKE '%директор по развитию%'
    OR title ILIKE '%директор по логистике%'
    OR title ILIKE '%директор по закупкам%'
    OR title ILIKE '%директор по качеству%'
    OR title ILIKE '%директор по производству%'
    OR title ILIKE '%директор по IT%'
    OR title ILIKE '%директор по информатизации%'
    OR title ILIKE '%директор по безопасности%'
    OR title ILIKE '%руководитель проекта%'
    OR title ILIKE '%руководитель направления%'
    OR title ILIKE '%руководитель отдела%'
    OR title ILIKE '%руководитель группы%'
    OR title ILIKE '%team lead%'
    OR title ILIKE '%tech lead%'
    OR title ILIKE '%head of%'
  );

-- Law Category
UPDATE vacancies
SET category = 'Право'
WHERE category IS NULL
  AND (
    title ILIKE '%юрист%'
    OR title ILIKE '%юрисконсульт%'
    OR title ILIKE '%адвокат%'
    OR title ILIKE '%нотариус%'
    OR title ILIKE '%судья%'
    OR title ILIKE '%прокурор%'
    OR title ILIKE '%следователь%'
    OR title ILIKE '%договор%'
    OR title ILIKE '%контракт%'
    OR title ILIKE '%лицензирование%'
    OR title ILIKE '%сертификация%'
    OR title ILIKE '%аккредитация%'
    OR title ILIKE '%экспертиза%'
    OR title ILIKE '%эксперт-оценщик%'
    OR title ILIKE '%оценщик%'
    OR title ILIKE '%регистратор%'
    OR title ILIKE '%миграционный%'
    OR title ILIKE '%визовый%'
    OR title ILIKE '%таможенный%'
    OR title ILIKE '%таможенник%'
    OR title ILIKE '%декларант%'
    OR title ILIKE '%брокер%'
    OR title ILIKE '%страховой%'
    OR title ILIKE '%страховой агент%'
    OR title ILIKE '%страховой брокер%'
    OR title ILIKE '%корпоративный юрист%'
    OR title ILIKE '%налоговый юрист%'
    OR title ILIKE '%трудовой юрист%'
    OR title ILIKE '%гражданский юрист%'
    OR title ILIKE '%уголовный юрист%'
    OR title ILIKE '%хозяйственный юрист%'
    OR title ILIKE '%финансовый юрист%'
    OR title ILIKE '%ипотечный юрист%'
    OR title ILIKE '%земельный юрист%'
    OR title ILIKE '%строительный юрист%'
    OR title ILIKE '%международный юрист%'
    OR title ILIKE '%морской юрист%'
    OR title ILIKE '%таможенный юрист%'
    OR title ILIKE '%экологический юрист%'
    OR title ILIKE '%медицинский юрист%'
    OR title ILIKE '%it юрист%'
    OR title ILIKE '%айти юрист%'
    OR title ILIKE '%digital юрист%'
    OR title ILIKE '%юрист по интеллектуальной собственности%'
    OR title ILIKE '%юрист по авторскому праву%'
    OR title ILIKE '%патентный поверенный%'
    OR title ILIKE '%патентный юрист%'
    OR title ILIKE '%юрист по недвижимости%'
    OR title ILIKE '%юрист по жкх%'
    OR title ILIKE '%юрист по семейным делам%'
    OR title ILIKE '%юрист по наследству%'
    OR title ILIKE '%юрист по банкротству%'
    OR title ILIKE '%юрист по арбитражу%'
    OR title ILIKE '%арбитражный управляющий%'
    OR title ILIKE '%судебный пристав%'
    OR title ILIKE '%комплаенс%'
    OR title ILIKE '%compliance%'
    OR title ILIKE '%внутренний аудитор%'
    OR title ILIKE '%контролер%'
    OR title ILIKE '%inspector%'
    OR title ILIKE '%инспектор%'
    OR title ILIKE '%ревизор%'
  );

-- Set remaining to 'Другое'
UPDATE vacancies
SET category = 'Другое'
WHERE category IS NULL;

-- 4. FINAL CHECK
SELECT 'FINAL RESULT' as info;
SELECT 
  category,
  COUNT(*) as count,
  ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM vacancies), 2) as percentage
FROM vacancies
GROUP BY category
ORDER BY count DESC;

-- 5. Verify total
SELECT 
  COUNT(*) as total_vacancies,
  COUNT(CASE WHEN category IS NULL THEN 1 END) as without_category
FROM vacancies;
