-- ============================================
-- Diagnostic: Check actual vacancy titles and categories
-- ============================================

-- 1. Check sample IT-related vacancies
SELECT title, category, company
FROM vacancies
WHERE LOWER(title) LIKE '%программист%'
   OR LOWER(title) LIKE '%developer%'
   OR LOWER(title) LIKE '%java%'
   OR LOWER(title) LIKE '%python%'
   OR LOWER(title) LIKE '%1с%'
   OR LOWER(title) LIKE '%it%'
LIMIT 20;

-- 2. Check current category distribution
SELECT 
  COALESCE(NULLIF(category, ''), 'БЕЗ КАТЕГОРИИ') as category,
  COUNT(*) as count
FROM vacancies
GROUP BY category
ORDER BY count DESC;

-- 3. Check some vacancies that should be IT but aren't
SELECT title, category
FROM vacancies
WHERE (LOWER(title) LIKE '%программист%' OR LOWER(title) LIKE '%разработчик%')
  AND (category IS NULL OR category = '' OR category != 'ИТ')
LIMIT 10;

-- 4. Show total count
SELECT COUNT(*) as total_vacancies FROM vacancies;

-- ============================================
-- FIX: Update categories using LIKE patterns (simpler and more reliable)
-- ============================================

-- First, reset categories for re-processing (optional - comment out if not needed)
-- UPDATE vacancies SET category = NULL;

-- Update IT category - multiple passes for different keyword groups
UPDATE vacancies
SET category = 'ИТ'
WHERE category IS NULL 
  AND (
    LOWER(title) LIKE '%программист%' 
    OR LOWER(title) LIKE '%разработчик%'
    OR LOWER(title) LIKE '%developer%'
    OR LOWER(title) LIKE '%инженер-программист%'
    OR LOWER(title) LIKE '%frontend%'
    OR LOWER(title) LIKE '%backend%'
    OR LOWER(title) LIKE '%fullstack%'
    OR LOWER(title) LIKE '%devops%'
    OR LOWER(title) LIKE '%qa%'
    OR LOWER(title) LIKE '%тестировщик%'
    OR LOWER(title) LIKE '%javascript%'
    OR LOWER(title) LIKE '%java%'
    OR LOWER(title) LIKE '%python%'
    OR LOWER(title) LIKE '%php%'
    OR LOWER(title) LIKE '%1с%'
    OR LOWER(title) LIKE '%1c%'
    OR LOWER(title) LIKE '%bitrix%'
    OR LOWER(title) LIKE '%битрикс%'
    OR LOWER(title) LIKE '%web%'
    OR LOWER(title) LIKE '%веб%'
    OR LOWER(title) LIKE '%mobile%'
    OR LOWER(title) LIKE '%мобильн%'
    OR LOWER(title) LIKE '%react%'
    OR LOWER(title) LIKE '%angular%'
    OR LOWER(title) LIKE '%vue%'
    OR LOWER(title) LIKE '%node%'
    OR LOWER(title) LIKE '%sql%'
    OR LOWER(title) LIKE '%database%'
    OR LOWER(title) LIKE '%база данных%'
    OR LOWER(title) LIKE '%it %'
    OR LOWER(title) LIKE '%айти%'
    OR LOWER(title) LIKE '%системный администратор%'
    OR LOWER(title) LIKE '%сисадмин%'
    OR LOWER(title) LIKE '%data scientist%'
    OR LOWER(title) LIKE '%data analyst%'
    OR LOWER(title) LIKE '%машинное обучение%'
    OR LOWER(title) LIKE '%machine learning%'
    OR LOWER(title) LIKE '%android%'
    OR LOWER(title) LIKE '%ios%'
    OR LOWER(title) LIKE '%swift%'
    OR LOWER(title) LIKE '%kotlin%'
    OR LOWER(title) LIKE '%golang%'
    OR LOWER(title) LIKE '%go %'
    OR LOWER(title) LIKE '%ruby%'
    OR LOWER(title) LIKE '%c++%'
    OR LOWER(title) LIKE '%c#%'
    OR LOWER(title) LIKE '%.net%'
    OR LOWER(title) LIKE '%aspnet%'
    OR LOWER(title) LIKE '%laravel%'
    OR LOWER(title) LIKE '%django%'
    OR LOWER(title) LIKE '%spring%'
    OR LOWER(title) LIKE '%hibernate%'
    OR LOWER(title) LIKE '%docker%'
    OR LOWER(title) LIKE '%kubernetes%'
    OR LOWER(title) LIKE '%aws%'
    OR LOWER(title) LIKE '%azure%'
    OR LOWER(title) LIKE '%cloud%'
    OR LOWER(title) LIKE '%облак%'
    OR LOWER(title) LIKE '%сети%'
    OR LOWER(title) LIKE '%network%'
    OR LOWER(title) LIKE '%кибербезопасность%'
    OR LOWER(title) LIKE '%cybersecurity%'
    OR LOWER(title) LIKE '%security%'
    OR LOWER(title) LIKE '%безопасность%'
  );

-- Update Medicine category
UPDATE vacancies
SET category = 'Медицина'
WHERE (category IS NULL OR category = '')
  AND (
    LOWER(title) LIKE '%врач%'
    OR LOWER(title) LIKE '%доктор%'
    OR LOWER(title) LIKE '%медицинский%'
    OR LOWER(title) LIKE '%медсестра%'
    OR LOWER(title) LIKE '%медбрат%'
    OR LOWER(title) LIKE '%фельдшер%'
    OR LOWER(title) LIKE '%стоматолог%'
    OR LOWER(title) LIKE '%хирург%'
    OR LOWER(title) LIKE '%терапевт%'
    OR LOWER(title) LIKE '%педиатр%'
    OR LOWER(title) LIKE '%кардиолог%'
    OR LOWER(title) LIKE '%невролог%'
    OR LOWER(title) LIKE '%офтальмолог%'
    OR LOWER(title) LIKE '%акушер%'
    OR LOWER(title) LIKE '%гинеколог%'
    OR LOWER(title) LIKE '%уролог%'
    OR LOWER(title) LIKE '%дерматолог%'
    OR LOWER(title) LIKE '%психиатр%'
    OR LOWER(title) LIKE '%психолог%'
    OR LOWER(title) LIKE '%фармацевт%'
    OR LOWER(title) LIKE '%провизор%'
    OR LOWER(title) LIKE '%лаборант%'
    OR LOWER(title) LIKE '%массажист%'
    OR LOWER(title) LIKE '%реабилитолог%'
    OR LOWER(title) LIKE '%диетолог%'
    OR LOWER(title) LIKE '%логопед%'
    OR LOWER(title) LIKE '%дефектолог%'
    OR LOWER(title) LIKE '%рентгенолог%'
    OR LOWER(title) LIKE '%эндоскопист%'
    OR LOWER(title) LIKE '%анестезиолог%'
    OR LOWER(title) LIKE '%реаниматолог%'
    OR LOWER(title) LIKE '%инфекционист%'
    OR LOWER(title) LIKE '%венеролог%'
    OR LOWER(title) LIKE '%фтизиатр%'
    OR LOWER(title) LIKE '%онколог%'
    OR LOWER(title) LIKE '%гематолог%'
    OR LOWER(title) LIKE '%эндокринолог%'
    OR LOWER(title) LIKE '%гастроэнтеролог%'
    OR LOWER(title) LIKE '%пульмонолог%'
    OR LOWER(title) LIKE '%нефролог%'
    OR LOWER(title) LIKE '%гепатолог%'
    OR LOWER(title) LIKE '%иммунолог%'
    OR LOWER(title) LIKE '%аллерголог%'
    OR LOWER(title) LIKE '%травматолог%'
    OR LOWER(title) LIKE '%ортопед%'
    OR LOWER(title) LIKE '%остеопат%'
    OR LOWER(title) LIKE '%косметолог%'
    OR LOWER(title) LIKE '%стоматолог%'
    OR LOWER(title) LIKE '%зубной%'
    OR LOWER(title) LIKE '%дантист%'
  );

-- Update Engineering category
UPDATE vacancies
SET category = 'Инженерия'
WHERE (category IS NULL OR category = '')
  AND (
    LOWER(title) LIKE '%инженер%'
    OR LOWER(title) LIKE '%engineer%'
    OR LOWER(title) LIKE '%конструктор%'
    OR LOWER(title) LIKE '%проектировщик%'
    OR LOWER(title) LIKE '%технолог%'
    OR LOWER(title) LIKE '%механик%'
    OR LOWER(title) LIKE '%электрик%'
    OR LOWER(title) LIKE '%электронщик%'
    OR LOWER(title) LIKE '%сварщик%'
    OR LOWER(title) LIKE '%токарь%'
    OR LOWER(title) LIKE '%фрезеровщик%'
    OR LOWER(title) LIKE '%слесарь%'
    OR LOWER(title) LIKE '%машинист%'
    OR LOWER(title) LIKE '%оператор станка%'
    OR LOWER(title) LIKE '%чпу%'
    OR LOWER(title) LIKE '%cnc%'
    OR LOWER(title) LIKE '%энергетик%'
    OR LOWER(title) LIKE '%строитель%'
    OR LOWER(title) LIKE '%прораб%'
    OR LOWER(title) LIKE '%прораб%'
    OR LOWER(title) LIKE '%мастер участка%'
    OR LOWER(title) LIKE '%архитектор%'
    OR LOWER(title) LIKE '%геодезист%'
    OR LOWER(title) LIKE '%геолог%'
    OR LOWER(title) LIKE '%нефтяник%'
    OR LOWER(title) LIKE '%газовщик%'
    OR LOWER(title) LIKE '%химик%'
    OR LOWER(title) LIKE '%эколог%'
    OR LOWER(title) LIKE '%сантехник%'
    OR LOWER(title) LIKE '%электромонтер%'
    OR LOWER(title) LIKE '%монтажник%'
    OR LOWER(title) LIKE '%сборщик%'
    OR LOWER(title) LIKE '%наладчик%'
    OR LOWER(title) LIKE '%метролог%'
    OR LOWER(title) LIKE '%стандартист%'
    OR LOWER(title) LIKE '%техник%'
    OR LOWER(title) LIKE '%лаборант производств%'
    OR LOWER(title) LIKE '%контролер%'
    OR LOWER(title) LIKE '%маляр%'
    OR LOWER(title) LIKE '%штукатур%'
    OR LOWER(title) LIKE '%плиточник%'
    OR LOWER(title) LIKE '%отделочник%'
    OR LOWER(title) LIKE '%плотник%'
    OR LOWER(title) LIKE '%столяр%'
    OR LOWER(title) LIKE '%электросварщик%'
    OR LOWER(title) LIKE '%газосварщик%'
    OR LOWER(title) LIKE '%арматурщик%'
    OR LOWER(title) LIKE '%бетонщик%'
    OR LOWER(title) LIKE '%железобетонщик%'
    OR LOWER(title) LIKE '%крановщик%'
    OR LOWER(title) LIKE '%машинист крана%'
    OR LOWER(title) LIKE '%машинист экскаватора%'
    OR LOWER(title) LIKE '%машинист бульдозера%'
    OR LOWER(title) LIKE '%тракторист%'
    OR LOWER(title) LIKE '%водитель погрузчика%'
    OR LOWER(title) LIKE '%карщик%'
  );

-- Update Education category
UPDATE vacancies
SET category = 'Педагогика'
WHERE (category IS NULL OR category = '')
  AND (
    LOWER(title) LIKE '%учитель%'
    OR LOWER(title) LIKE '%преподаватель%'
    OR LOWER(title) LIKE '%педагог%'
    OR LOWER(title) LIKE '%воспитатель%'
    OR LOWER(title) LIKE '%няня%'
    OR LOWER(title) LIKE '%гувернантка%'
    OR LOWER(title) LIKE '%методист%'
    OR LOWER(title) LIKE '%репетитор%'
    OR LOWER(title) LIKE '%тьютор%'
    OR LOWER(title) LIKE '%завуч%'
    OR LOWER(title) LIKE '%директор школы%'
    OR LOWER(title) LIKE '%директор детского сада%'
    OR LOWER(title) LIKE '%заведующий%'
    OR LOWER(title) LIKE '%декан%'
    OR LOWER(title) LIKE '%ректор%'
    OR LOWER(title) LIKE '%проректор%'
    OR LOWER(title) LIKE '%завкафедрой%'
    OR LOWER(title) LIKE '%заведующий кафедрой%'
    OR LOWER(title) LIKE '%аспирант%'
    OR LOWER(title) LIKE '%старший преподаватель%'
    OR LOWER(title) LIKE '%доцент%'
    OR LOWER(title) LIKE '%профессор%'
    OR LOWER(title) LIKE '%научный сотрудник%'
    OR LOWER(title) LIKE '%исследователь%'
    OR LOWER(title) LIKE '%логопед%'
    OR LOWER(title) LIKE '%дефектолог%'
    OR LOWER(title) LIKE '%психолог образовательный%'
    OR LOWER(title) LIKE '%социальный педагог%'
    OR LOWER(title) LIKE '%инструктор%'
    OR LOWER(title) LIKE '%тренер%'
    OR LOWER(title) LIKE '%преподаватель вождения%'
    OR LOWER(title) LIKE '%учитель вождения%'
    OR LOWER(title) LIKE '%преподаватель иностранного языка%'
    OR LOWER(title) LIKE '%учитель английского%'
    OR LOWER(title) LIKE '%учитель немецкого%'
    OR LOWER(title) LIKE '%учитель французского%'
    OR LOWER(title) LIKE '%учитель математики%'
    OR LOWER(title) LIKE '%учитель физики%'
    OR LOWER(title) LIKE '%учитель химии%'
    OR LOWER(title) LIKE '%учитель биологии%'
    OR LOWER(title) LIKE '%учитель истории%'
    OR LOWER(title) LIKE '%учитель географии%'
    OR LOWER(title) LIKE '%учитель литературы%'
    OR LOWER(title) LIKE '%учитель русского языка%'
    OR LOWER(title) LIKE '%учитель белорусского%'
    OR LOWER(title) LIKE '%учитель начальных классов%'
    OR LOWER(title) LIKE '%учитель начальных%'
    OR LOWER(title) LIKE '%учитель музыки%'
    OR LOWER(title) LIKE '%учитель рисования%'
    OR LOWER(title) LIKE '%учитель физкультуры%'
    OR LOWER(title) LIKE '%учитель технологии%'
    OR LOWER(title) LIKE '%учитель информатики%'
  );

-- Update Economics category
UPDATE vacancies
SET category = 'Экономика'
WHERE (category IS NULL OR category = '')
  AND (
    LOWER(title) LIKE '%бухгалтер%'
    OR LOWER(title) LIKE '%главный бухгалтер%'
    OR LOWER(title) LIKE '%бухгалтер-кассир%'
    OR LOWER(title) LIKE '%экономист%'
    OR LOWER(title) LIKE '%финансист%'
    OR LOWER(title) LIKE '%аудитор%'
    OR LOWER(title) LIKE '%кредитный специалист%'
    OR LOWER(title) LIKE '%кредитный эксперт%'
    OR LOWER(title) LIKE '%специалист по кредитованию%'
    OR LOWER(title) LIKE '%банкир%'
    OR LOWER(title) LIKE '%сотрудник банка%'
    OR LOWER(title) LIKE '%кассир банка%'
    OR LOWER(title) LIKE '%операционист%'
    OR LOWER(title) LIKE '%инвестиционный%'
    OR LOWER(title) LIKE '%аналитик%'
    OR LOWER(title) LIKE '%финансовый аналитик%'
    OR LOWER(title) LIKE '%экономический аналитик%'
    OR LOWER(title) LIKE '%бизнес-аналитик%'
    OR LOWER(title) LIKE '%системный аналитик%'
    OR LOWER(title) LIKE '%маркетолог%'
    OR LOWER(title) LIKE '%специалист по маркетингу%'
    OR LOWER(title) LIKE '%smm%'
    OR LOWER(title) LIKE '%seo%'
    OR LOWER(title) LIKE '%контекстная реклама%'
    OR LOWER(title) LIKE '%таргетолог%'
    OR LOWER(title) LIKE '%копирайтер%'
    OR LOWER(title) LIKE '%content manager%'
    OR LOWER(title) LIKE '%менеджер по продажам%'
    OR LOWER(title) LIKE '%менеджер по работе с клиентами%'
    OR LOWER(title) LIKE '%менеджер по ключевым клиентам%'
    OR LOWER(title) LIKE '%account manager%'
    OR LOWER(title) LIKE '%sales manager%'
    OR LOWER(title) LIKE '%торговый представитель%'
    OR LOWER(title) LIKE '%продавец%'
    OR LOWER(title) LIKE '%продавец-консультант%'
    OR LOWER(title) LIKE '%продавец-кассир%'
    OR LOWER(title) LIKE '%кассир%'
    OR LOWER(title) LIKE '%старший кассир%'
    OR LOWER(title) LIKE '%консультант%'
    OR LOWER(title) LIKE '%специалист по работе с клиентами%'
    OR LOWER(title) LIKE '%клиентский менеджер%'
    OR LOWER(title) LIKE '%hr%'
    OR LOWER(title) LIKE '%hr-менеджер%'
    OR LOWER(title) LIKE '%специалист по подбору персонала%'
    OR LOWER(title) LIKE '%рекрутер%'
    OR LOWER(title) LIKE '%кадровик%'
    OR LOWER(title) LIKE '%специалист по кадрам%'
    OR LOWER(title) LIKE '%директор по персоналу%'
    OR LOWER(title) LIKE '%hr director%'
    OR LOWER(title) LIKE '%менеджер по персоналу%'
    OR LOWER(title) LIKE '%логист%'
    OR LOWER(title) LIKE '%специалист по логистике%'
    OR LOWER(title) LIKE '%менеджер по логистике%'
    OR LOWER(title) LIKE '%транспортный логист%'
    OR LOWER(title) LIKE '%склад%'
    OR LOWER(title) LIKE '%кладовщик%'
    OR LOWER(title) LIKE '%начальник склада%'
    OR LOWER(title) LIKE '%менеджер склада%'
    OR LOWER(title) LIKE '%комплектовщик%'
    OR LOWER(title) LIKE '%грузчик%'
    OR LOWER(title) LIKE '%экспедитор%'
    OR LOWER(title) LIKE '%диспетчер%'
    OR LOWER(title) LIKE '%транспортный диспетчер%'
    OR LOWER(title) LIKE '%водитель%'
    OR LOWER(title) LIKE '%водитель-экспедитор%'
    OR LOWER(title) LIKE '%курьер%'
    OR LOWER(title) LIKE '%закупщик%'
    OR LOWER(title) LIKE '%менеджер по закупкам%'
    OR LOWER(title) LIKE '%специалист по закупкам%'
    OR LOWER(title) LIKE '%снабженец%'
    OR LOWER(title) LIKE '%товаровед%'
    OR LOWER(title) LIKE '%мерчандайзер%'
    OR LOWER(title) LIKE '%промоутер%'
    OR LOWER(title) LIKE '%хостес%'
    OR LOWER(title) LIKE '%официант%'
    OR LOWER(title) LIKE '%бармен%'
    OR LOWER(title) LIKE '%бариста%'
    OR LOWER(title) LIKE '%шеф-повар%'
    OR LOWER(title) LIKE '%повар%'
    OR LOWER(title) LIKE '%кондитер%'
    OR LOWER(title) LIKE '%пекарь%'
    OR LOWER(title) LIKE '%сушист%'
    OR LOWER(title) LIKE '%пиццмейкер%'
    OR LOWER(title) LIKE '%менеджер ресторана%'
    OR LOWER(title) LIKE '%управляющий рестораном%'
    OR LOWER(title) LIKE '%администратор ресторана%'
    OR LOWER(title) LIKE '%менеджер гостиницы%'
    OR LOWER(title) LIKE '%администратор гостиницы%'
    OR LOWER(title) LIKE '%горничная%'
    OR LOWER(title) LIKE '%портье%'
    OR LOWER(title) LIKE '%рекception%'
    OR LOWER(title) LIKE '%секретарь%'
    OR LOWER(title) LIKE '%делопроизводитель%'
    OR LOWER(title) LIKE '%офис-менеджер%'
    OR LOWER(title) LIKE '%администратор офиса%'
    OR LOWER(title) LIKE '%помощник руководителя%'
    OR LOWER(title) LIKE '%ассистент%'
    OR LOWER(title) LIKE '%личный помощник%'
    OR LOWER(title) LIKE '%переводчик%'
    OR LOWER(title) LIKE '%стажер%'
    OR LOWER(title) LIKE '%intern%'
    OR LOWER(title) LIKE '%менеджер%'
    OR LOWER(title) LIKE '%руководитель%'
    OR LOWER(title) LIKE '%директор%'
    OR LOWER(title) LIKE '%начальник отдела%'
    OR LOWER(title) LIKE '%начальник управления%'
    OR LOWER(title) LIKE '%заместитель директора%'
    OR LOWER(title) LIKE '%генеральный директор%'
    OR LOWER(title) LIKE '%коммерческий директор%'
    OR LOWER(title) LIKE '%исполнительный директор%'
    OR LOWER(title) LIKE '%финансовый директор%'
    OR LOWER(title) LIKE '%операционный директор%'
    OR LOWER(title) LIKE '%директор по маркетингу%'
    OR LOWER(title) LIKE '%директор по продажам%'
    OR LOWER(title) LIKE '%директор по персоналу%'
    OR LOWER(title) LIKE '%директор по развитию%'
    OR LOWER(title) LIKE '%директор по логистике%'
    OR LOWER(title) LIKE '%директор по закупкам%'
    OR LOWER(title) LIKE '%директор по качеству%'
    OR LOWER(title) LIKE '%директор по производству%'
    OR LOWER(title) LIKE '%директор по IT%'
    OR LOWER(title) LIKE '%директор по информатизации%'
    OR LOWER(title) LIKE '%директор по безопасности%'
    OR LOWER(title) LIKE '%руководитель проекта%'
    OR LOWER(title) LIKE '%руководитель направления%'
    OR LOWER(title) LIKE '%руководитель отдела%'
    OR LOWER(title) LIKE '%руководитель группы%'
    OR LOWER(title) LIKE '%team lead%'
    OR LOWER(title) LIKE '%tech lead%'
    OR LOWER(title) LIKE '%head of%'
  );

-- Update Law category
UPDATE vacancies
SET category = 'Право'
WHERE (category IS NULL OR category = '')
  AND (
    LOWER(title) LIKE '%юрист%'
    OR LOWER(title) LIKE '%юрисконсульт%'
    OR LOWER(title) LIKE '%юридический%'
    OR LOWER(title) LIKE '%адвокат%'
    OR LOWER(title) LIKE '%нотариус%'
    OR LOWER(title) LIKE '%судья%'
    OR LOWER(title) LIKE '%прокурор%'
    OR LOWER(title) LIKE '%следователь%'
    OR LOWER(title) LIKE '%юрисконсульт%'
    OR LOWER(title) LIKE '%правовой%'
    OR LOWER(title) LIKE '%договор%'
    OR LOWER(title) LIKE '%контракт%'
    OR LOWER(title) LIKE '%лицензирование%'
    OR LOWER(title) LIKE '%сертификация%'
    OR LOWER(title) LIKE '%аккредитация%'
    OR LOWER(title) LIKE '%экспертиза%'
    OR LOWER(title) LIKE '%эксперт-оценщик%'
    OR LOWER(title) LIKE '%оценщик%'
    OR LOWER(title) LIKE '%регистратор%'
    OR LOWER(title) LIKE '%миграционный%'
    OR LOWER(title) LIKE '%визовый%'
    OR LOWER(title) LIKE '%таможенный%'
    OR LOWER(title) LIKE '%таможенник%'
    OR LOWER(title) LIKE '%декларант%'
    OR LOWER(title) LIKE '%брокер%'
    OR LOWER(title) LIKE '%страховой%'
    OR LOWER(title) LIKE '%страховой агент%'
    OR LOWER(title) LIKE '%страховой брокер%'
    OR LOWER(title) LIKE '%юридический консультант%'
    OR LOWER(title) LIKE '%корпоративный юрист%'
    OR LOWER(title) LIKE '%налоговый юрист%'
    OR LOWER(title) LIKE '%трудовой юрист%'
    OR LOWER(title) LIKE '%гражданский юрист%'
    OR LOWER(title) LIKE '%уголовный юрист%'
    OR LOWER(title) LIKE '%хозяйственный юрист%'
    OR LOWER(title) LIKE '%финансовый юрист%'
    OR LOWER(title) LIKE '%ипотечный юрист%'
    OR LOWER(title) LIKE '%земельный юрист%'
    OR LOWER(title) LIKE '%строительный юрист%'
    OR LOWER(title) LIKE '%международный юрист%'
    OR LOWER(title) LIKE '%морской юрист%'
    OR LOWER(title) LIKE '%таможенный юрист%'
    OR LOWER(title) LIKE '%экологический юрист%'
    OR LOWER(title) LIKE '%медицинский юрист%'
    OR LOWER(title) LIKE '%it юрист%'
    OR LOWER(title) LIKE '%айти юрист%'
    OR LOWER(title) LIKE '%digital юрист%'
    OR LOWER(title) LIKE '%юрист по интеллектуальной собственности%'
    OR LOWER(title) LIKE '%юрист по авторскому праву%'
    OR LOWER(title) LIKE '%патентный поверенный%'
    OR LOWER(title) LIKE '%патентный юрист%'
    OR LOWER(title) LIKE '%юрист по недвижимости%'
    OR LOWER(title) LIKE '%юрист по жкх%'
    OR LOWER(title) LIKE '%юрист по семейным делам%'
    OR LOWER(title) LIKE '%юрист по наследству%'
    OR LOWER(title) LIKE '%юрист по банкротству%'
    OR LOWER(title) LIKE '%юрист по арбитражу%'
    OR LOWER(title) LIKE '%арбитражный управляющий%'
    OR LOWER(title) LIKE '%судебный пристав%'
    OR LOWER(title) LIKE '%исполнительный директор%'
    OR LOWER(title) LIKE '%комплаенс%'
    OR LOWER(title) LIKE '%compliance%'
    OR LOWER(title) LIKE '%аудитор%'
    OR LOWER(title) LIKE '%внутренний аудитор%'
    OR LOWER(title) LIKE '%контролер%'
    OR LOWER(title) LIKE '%inspector%'
    OR LOWER(title) LIKE '%инспектор%'
    OR LOWER(title) LIKE '%ревизор%'
  );

-- Set remaining uncategorized to 'Другое'
UPDATE vacancies
SET category = 'Другое'
WHERE category IS NULL OR category = '';

-- Final check - show distribution
SELECT 
  category,
  COUNT(*) as count,
  ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM vacancies), 2) as percentage
FROM vacancies
GROUP BY category
ORDER BY count DESC;

-- Show total
SELECT COUNT(*) as total_vacancies FROM vacancies;
SELECT 
  SUM(CASE WHEN category IS NULL OR category = '' THEN 1 ELSE 0 END) as without_category
FROM vacancies;
